version: "3.9"

services:
  feeder:
    image: docker-registry.rahti.csc.fi/student474/toyota-data:1.0
    environment:
      - MQTT_URL=mqtt-test.rahtiapp.fi
      - MQTT_PORT=8883
      - CLIENT_ID=student474
    networks:
      - student474-net
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
     - "1883:8883"
    volumes:
     - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
     - "./ca.crt:/mosquitto/certs/ca.crt"
     - "./server.crt:/mosquitto/certs/server.crt"
     - "./server.key:/mosquitto/certs/server.key"
    command: mosquitto_sub -h mqtt-test.rahtiapp.fi -p 8883 -t 'student474/toyota/SPEED' --verbose --insecure --cafile /mosquitto/certs/ca.crt
    networks:
      - student474-net
networks:
  student474-net:

