version: "3.7"

services:
  feeder:
    image: docker-registry.rahti.csc.fi/student474/toyota-data:1.0
    environment:
      - MQTT_URL=mosquitto
      - MQTT_PORT=1883
      - CLIENT_ID=student474
    networks:
      - student474-net
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
     - "8883:1883"
    volumes:
     - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
     - "./ca.crt:/mosquitto/certs/ca.crt"
     - "./server.crt:/mosquitto/certs/server.crt"
     - "./server.key:/mosquitto/certs/server.key"
    networks:
      - student474-net

networks:
  student474-net:

