version: "3.7"

services:
  feeder:
    image: docker-registry.rahti.csc.fi/student474/toyota-data:1.0
    environment:
      - MQTT_URL=localhost
      - MQTT_PORT=8883
      - CLIENT_ID=student474
    networks:
      - default
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
     - "1883:8883"
    volumes:
     - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
     - "./ca.crt:/mosquitto/certs/ca.crt"
     - "./server.crt:/mosquitto/certs/server.crt"
     - "./server.key:/mosquitto/certs/server.key"
    networks:
      - default

networks:
  default:
    external:
      name: host

