apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-secret
              mountPath: /mosquitto/config/certs
              readOnly: true
          command: ["mosquitto_sub -h mqtt.student474.rahtiapp.fi -p 443 -t 'student474/toyota/SPEED' --verbose --insecure --cafile /mosquitto/config/certs/ca.crt"]
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-configmap
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret-file
