apiVersion: v1
data:
  mosquitto.conf: |-
  listener 1883
  allow_anonymous true

  listener 8883
  cafile /mosquitto/config/certs/ca.crt
  certfile /mosquitto/config/certs/server.crt
  keyfile /mosquitto/config/certs/server.key
  require_certificate false

kind: ConfigMap
metadata:
  name: mosquitto-configmap
  labels:
    app: mosquitto
