apiVersion: v1
data:
  mosquitto.conf: |-
    listener 8883

    allow_anonymous true
    cafile /mosquitto/config/certs/ca.crt
    certfile /mosquitto/config/certs/server.crt
    keyfile /mosquitto/config/certs/server.key
    require_certificate true

    listener 1883

kind: ConfigMap
metadata:
  name: mosquitto-configmap
  labels:
    app: mosquitto
