apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      name: mosquittoport1
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: mosquittoport2
      port: 8883
      targetPort: 8883